### PR TITLE
Upgrade to python-cpl 0.7.4

### PR DESCRIPTION
**Pull request by hugobuddel**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Upgrades python-cpl version to 0.7.4. Also brings the build system up to date and should thereby add Python 3.8 and 3.9 support.

### CODE REVIEW

**Comment by hugobuddel** [comment]
@bsipocz this should make the conda python-cpl package up-to-date with the pip one.

Note that we also have a pull request to make a conda recipe for cpl itself: https://github.com/conda-forge/staged-recipes/pull/18178 Once that is merged, we can make it a dependency of python-cpl. Then we have everything in place to make conda packages of actual ESO pipelines.

**Comment by bsipocz** [comment]
@hugobuddel - shouldn't you be listed as a maintainer for this feedstock, too? I'll wait for that before pushing the merge button.

**Comment by hugobuddel** [comment]
@bsipocz , I've added myself to the feedstock maintainers.

As I understand it, maintainers are more than just contributors: they have push access to the feedstock and are able to merge MR's etc. I'm happy to join you in that role if that is okay with you.

**Comment by bsipocz** [comment]
Given that you'll be a maintainer for the `cpl-feedstock` I think it makes much sense to have it here, too to be able to merge PRs.

**Comment by hugobuddel** [comment]
Thanks @bsipocz , the [bot has given me maintainer rights](https://github.com/conda-forge/python-cpl-feedstock/commit/66b7a177eae980fe9ea4c6ce9a92323a6c8e425f#commitcomment-68283464). I've tested those by merging #11, so there now also should be Python 3.10 support.

**Pull request merged**
